import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import { BodyColor } from "../components/BodyColor";
import { Greeting } from "../components/Greeting";
import { PostListItem } from "../components/PostListItem";
import { SectionTitle } from "../components/SectionTitle";
import { ThemeProvider } from "../components/ThemeProvider";
import { Header } from "./Header";
import { Footer } from "./Footer";

const StyledWrapper = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
`;

const StyledPageContent = styled.div`
  margin-top: 20px;
  width: 90%;
`;

const StyledMain = styled.main`
  padding: 60px 180px;
`;

const StyledPostList = styled.div`
  display: flex;
  flex-direction: column;
  gap: 25px;
`;

const StyledSectionTitle = styled(SectionTitle)`
  margin-top: 80px;
`;

const Home: NextPage = () => {
  return (
    <StyledWrapper>
      <StyledPageContent>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ThemeProvider>
          <BodyColor />
          <Header />
          <StyledMain>
            <Greeting />
            <StyledSectionTitle>Posts</StyledSectionTitle>
            <StyledPostList>
              <PostListItem
                title={"Everything you need to know about React 18"}
                date="2020-05-01T12:43:00Z"
                tags={["javascript", "react", "typescript"]}
              />
              <PostListItem
                title={"Everything you need to know about React 18"}
                date="2020-05-01T12:43:00Z"
                tags={["javascript", "react", "typescript"]}
              />
              <PostListItem
                title={"Everything you need to know about React 18"}
                date="2020-05-01T12:43:00Z"
                tags={["javascript", "react", "typescript"]}
              />
              <PostListItem
                title={"Everything you need to know about React 18"}
                date="2020-05-01T12:43:00Z"
                tags={["javascript", "react", "typescript"]}
              />
            </StyledPostList>
          </StyledMain>
          <Footer />
        </ThemeProvider>
      </StyledPageContent>
    </StyledWrapper>
  );
};

export default Home;
